### PR TITLE
Change the option from 'Ingest metadata only' to 'Ingest full event data' and make it off by default

### PR DESCRIPTION
**Pull request by TyMarc**
https://github.com/user-attachments/assets/d53a2256-cc85-4ca5-97b8-584cab301ee2

### CODE REVIEW

**Comment by aviau** [comment]
so fastttt

**Comment by aviau** [comment]
I imagine we need a frontend change too? Can you post a screenshot?

**Comment by TyMarc** [comment]
Added video in description @aviau

**Comment by aviau** [comment]
Can we reverse the checkbox?

Name it "Full Event Ingestion", and turn it off by default.

**Comment by TyMarc** [comment]
@aviau I updated the video

**Review by aviau — APPROVED** [review]

**Pull request merged**
